(autoload 'js2-mode "js2-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.js$" . js2-mode))
(custom-set-variables '(js2-basic-offset 2))
(add-hook 'js2-mode-hook 'flycheck-mode)
(add-hook 'js2-mode-hook 'highlight-symbol-mode)
